-- ============================================================
-- Plane to Car — Supabase Database Schema
-- Run this in: Supabase Dashboard > SQL Editor > New Query
-- ============================================================

-- Profiles table (extends auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT CHECK (role IN ('passenger', 'concierge', 'admin')) DEFAULT 'passenger',
  phone_number TEXT,
  verification_status TEXT CHECK (verification_status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Airports table
CREATE TABLE airports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Service Tiers table
CREATE TABLE service_tiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bookings table
CREATE TABLE bookings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  passenger_id UUID REFERENCES profiles(id) NOT NULL,
  concierge_id UUID REFERENCES profiles(id),
  airport_id BIGINT REFERENCES airports(id) NOT NULL,
  service_tier_id BIGINT REFERENCES service_tiers(id) NOT NULL,
  flight_number TEXT NOT NULL,
  arrival_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT CHECK (status IN ('pending', 'assigned', 'passenger_arrived', 'passenger_met', 'baggage_assistance', 'escort_in_progress', 'completed', 'cancelled')) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Booking status audit log
CREATE TABLE booking_status_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id UUID REFERENCES bookings(id) ON DELETE CASCADE NOT NULL,
  status TEXT NOT NULL,
  changed_by UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- Seed Data
-- ============================================================

INSERT INTO airports (name, code) VALUES
  ('Murtala Muhammed International Airport', 'LOS'),
  ('Nnamdi Azikiwe International Airport', 'ABV'),
  ('Port Harcourt International Airport', 'PHC'),
  ('Mallam Aminu Kano International Airport', 'KAN');

INSERT INTO service_tiers (name, description, price) VALUES
  ('Economy Fast-Track', 'Basic fast-track through immigration', 50.00),
  ('Premium Concierge', 'Fast-track + Baggage assistance', 100.00),
  ('VIP Luxury', 'Fast-track + Baggage + Executive escort to vehicle', 200.00);

-- ============================================================
-- Row Level Security (RLS)
-- Note: The backend uses the service role key which bypasses RLS.
-- These policies protect against direct client-side Supabase access.
-- ============================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_status_logs ENABLE ROW LEVEL SECURITY;

-- Profiles: users can only read their own profile (not all profiles)
CREATE POLICY "Users can view own profile." ON profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile." ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Bookings: strict ownership policies
CREATE POLICY "Passengers can view own bookings." ON bookings
  FOR SELECT USING (auth.uid() = passenger_id);

CREATE POLICY "Concierges can view assigned bookings." ON bookings
  FOR SELECT USING (auth.uid() = concierge_id);

CREATE POLICY "Admins can view all bookings." ON bookings
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Passengers can create own bookings." ON bookings
  FOR INSERT WITH CHECK (auth.uid() = passenger_id);

-- Booking status logs: only readable by the concierge or passenger involved
CREATE POLICY "Booking participants can view status logs." ON booking_status_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM bookings
      WHERE bookings.id = booking_status_logs.booking_id
        AND (bookings.passenger_id = auth.uid() OR bookings.concierge_id = auth.uid())
    )
  );
